# NOTE: This docker-compose.yml is meant to be just an example of how
# you could accomplish this on your own. It is not intended to work in
# all use-cases and must be adapted to fit your needs. This is merely
# a guideline.

# See docs.getsentry.com/on-premise/server/ for full
# instructions

version: '2'
services:
  base:
    build: .
    restart: always
    environment:
      # Run `docker-compose run web config generate-secret-key`
      # to get the SENTRY_SECRET_KEY value.
      # SENTRY_SECRET_KEY: ''
      SENTRY_MEMCACHED_HOST: memcached
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_EMAIL_HOST: smtp
    volumes:
      - "sentry-data:/var/lib/sentry/files"
    networks:
      - main-tier

  smtp:
    image: tianon/exim4
    restart: always
    networks:
      - main-tier

  memcached:
    image: memcached:1.4
    restart: always
    networks:
      - main-tier

  redis:
    image: redis:3.2-alpine
    restart: always
    networks:
      - main-tier

  postgres:
    image: postgres:9.5
    restart: always
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    networks:
      - main-tier

  web:
    extends: base
    restart: always
    depends_on:
      - redis
      - postgres
      - memcached
      - smtp
    networks:
      - main-tier

  cron:
    extends: base
    command: run cron
    restart: always
    depends_on:
      - redis
      - postgres
      - memcached
      - smtp
    networks:
      - main-tier

  worker:
    extends: base
    command: run worker
    restart: always
    depends_on:
      - redis
      - postgres
      - memcached
      - smtp
    networks:
      - main-tier

  proxy:
    build: nginx
    restart: always
    depends_on:
      - web
    ports:
      - "${NGINX_PUBLIC_PORT}:80"
      - "${NGINX_PUBLIC_SSL_PORT}:443"
    networks:
      - main-tier


volumes:
  sentry-data:
    external:
      name: "${SENTRY_VOLUME}"

  postgres-data:
    external:
      name: "${DB_VOLUME}"


networks:
  main-tier:
    external:
      name: "${NETWORK_NAME}"
